"""Handles asynchronous project creation, VS Code launching, and Spider-Man overlay start."""

import sys
import time
import subprocess
from pathlib import Path
import threading

DETACHED = subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP

class ProjectLauncher:
    def __init__(self):
        self.status = "IDLE"  # IDLE, CREATING, CREATED, LAUNCHING, DONE, ERROR_PROJECT, ERROR_VSCODE
        self.project_dir = None

    def create_project_async(self):
        if self.status != "IDLE":
            return
        self.status = "CREATING"
        threading.Thread(target=self._create_project_worker, daemon=True).start()

    def _create_project_worker(self):
        try:
            base_dir = Path.home() / "Desktop" / "STARK_PROJECTS"
            base_dir.mkdir(parents=True, exist_ok=True)
            
            project_name = f"STARK_PROJECT_{int(time.time())}"
            self.project_dir = base_dir / project_name
            self.project_dir.mkdir(parents=True, exist_ok=True)
            
            main_py = self.project_dir / "main.py"
            main_py_content = '''print("========================================")
print("          STARK // CODE ONLINE")
print("========================================")
print()
print("SANCTUM CORE ONLINE")
print("AVENGERS, ASSEMBLE.")
print()

developer = "STARK DEVELOPER"

print()
print(f"Welcome, {developer}.")
print("Developer environment initialized.")
print("All systems operational.")
'''
            main_py.write_text(main_py_content, encoding="utf-8")
            
            readme = self.project_dir / "README.md"
            readme_content = '''# STARK // CODE

Avengers-inspired developer workspace generated by the STARK//CODE Sanctum.

AVENGERS, ASSEMBLE.
'''
            readme.write_text(readme_content, encoding="utf-8")
            
            time.sleep(0.5)  # slight padding for cinematic feel
            self.status = "CREATED"
        except Exception as e:
            print(f"Error creating project: {e}")
            self.status = "ERROR_PROJECT"

    def launch_vscode_async(self):
        if self.status != "CREATED":
            return
        self.status = "LAUNCHING"
        threading.Thread(target=self._launch_vscode_worker, daemon=True).start()

    def _launch_vscode_worker(self):
        try:
            res = subprocess.run(["where", "code"], capture_output=True, shell=True)
            if res.returncode != 0:
                print("VS Code not found in PATH.")
                self.status = "ERROR_VSCODE"
                return

            # Launch VS Code maximized via PowerShell start command without visible console
            subprocess.Popen(
                ["powershell", "-WindowStyle", "Hidden", "-Command",
                 f'Start-Process code -ArgumentList "--new-window","--max-restore","{self.project_dir}"'],
                shell=False,
                creationflags=subprocess.CREATE_NO_WINDOW
            )

            # Wait for VS Code to be visible before launching the overlay
            time.sleep(2.5)

            # Launch the Spider-Man overlay as a fully independent detached process
            # so it survives the STARK//CODE window closing, hiding the console window
            overlay_script = Path(__file__).resolve().parent / "spider_web_overlay_test.py"
            subprocess.Popen(
                [sys.executable, str(overlay_script),
                 "--project-dir", str(self.project_dir)],
                cwd=str(Path(__file__).resolve().parent),
                creationflags=DETACHED | subprocess.CREATE_NO_WINDOW,
                close_fds=True,
            )
            print(f"[STARK] Spider-Man overlay launched as detached process.")

            self.status = "DONE"
        except Exception as e:
            print(f"Error launching VS Code: {e}")
            self.status = "ERROR_VSCODE"
