"""Handles asynchronous project creation and VS Code launching."""

import time
import subprocess
from pathlib import Path
import threading

class ProjectLauncher:
    def __init__(self):
        self.status = "IDLE"  # IDLE, CREATING, CREATED, LAUNCHING, DONE, ERROR_PROJECT, ERROR_VSCODE
        self.project_dir = None

    def create_project_async(self):
        if self.status != "IDLE":
            return
        self.status = "CREATING"
        threading.Thread(target=self._create_project_worker, daemon=True).start()

    def _create_project_worker(self):
        try:
            base_dir = Path.home() / "Desktop" / "STARK_PROJECTS"
            base_dir.mkdir(parents=True, exist_ok=True)
            
            project_name = f"STARK_PROJECT_{int(time.time())}"
            self.project_dir = base_dir / project_name
            self.project_dir.mkdir(parents=True, exist_ok=True)
            
            main_py = self.project_dir / "main.py"
            main_py.write_text('print("Welcome to STARK//CODE")\n', encoding="utf-8")
            
            readme = self.project_dir / "README.md"
            readme.write_text(f"# {project_name}\n\nGenerated by STARK//CODE Sanctum.\n", encoding="utf-8")
            
            time.sleep(0.5)  # slight padding for cinematic feel
            self.status = "CREATED"
        except Exception as e:
            print(f"Error creating project: {e}")
            self.status = "ERROR_PROJECT"

    def launch_vscode_async(self):
        if self.status != "CREATED":
            return
        self.status = "LAUNCHING"
        threading.Thread(target=self._launch_vscode_worker, daemon=True).start()

    def _launch_vscode_worker(self):
        try:
            res = subprocess.run(["where", "code"], capture_output=True, shell=True)
            if res.returncode != 0:
                print("VS Code not found in PATH.")
                self.status = "ERROR_VSCODE"
                return

            subprocess.Popen(["code", str(self.project_dir)], shell=True)
            time.sleep(1.0)
            self.status = "DONE"
        except Exception as e:
            print(f"Error launching VS Code: {e}")
            self.status = "ERROR_VSCODE"
